// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplicationApiDemo.Models;

[Table("AccessPolicy")]
public partial class AccessPolicy
{
    [Key]
    public int PolicyId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Permissions { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AllowedCaller { get; set; }
}